

;
; +-------------------------------------------------------------------------+
; |   This file	has been generated by The Interactive Disassembler (IDA)    |
; |	   Copyright (c) 2009 by Hex-Rays, <support@hex-rays.com>	    |
; |			 License info: E7-EC05-8A45-34			    |
; |				 Licensed User				    |
; +-------------------------------------------------------------------------+
;
; Input	MD5   :	ADCBF5BCCD613B34F0779526E804EC3E

; ---------------------------------------------------------------------------
; File Name   :	D:\cygwin\home\Erop\OS\boot.bin
; Format      :	Binary file
; Base Address:	0000h Range: 0000h - 0200h Loaded length: 0200h

		.686p
		.mmx
		.model flat

; ===========================================================================

; Segment type:	Pure code
seg000		segment	byte public 'CODE' use32
		assume cs:seg000
		assume es:nothing, ss:nothing, ds:nothing, fs:nothing, gs:nothing
		cli
		xor	eax, eax
		mov	ss, ax
		mov	esp, 0E5897BECh
		mov	ds, ax
		mov	esi, 0C08E7C00h
		mov	edi, 0B90600h
		add	esp, edi
		rep movsd
		jmp	far ptr	0C030h:61Fh
; ---------------------------------------------------------------------------
		cmp	dl, al
		jnz	short loc_27
		mov	dl, 80h	; '€'

loc_27:					; CODE XREF: seg000:00000023j
		mov	[esi+12h], dl
		mov	esi, 20BF0790h
		pop	es
		call	edi
		mov	esi, 4B907BEh
		add	[eax+eax*4+5C8AC030h], dh
		add	[eax], bh
		fdiv	qword ptr [ebx+edx+38h]
		fdiv	dword ptr [ebp+1Fh]
		add	esi, 75490010h
		out	dx, al
		mov	esi, 0FDBF0733h
		push	es
		call	edi
		mov	edi, esi

loc_58:					; CODE XREF: seg000:00000064j
		add	esi, 74490010h
		jp	near ptr 0DC3800C0h
		jnz	short loc_58
		mov	esi, 0FDBF074Ah
		push	es
		call	edi
		mov	ah, 41h	; 'A'
		mov	ebx, 568A55AAh
		adc	cl, ch
		adc	esi, [edx+50h]
		cmp	ebx, 4A75AA55h
		and	ecx, 44740001h
		mov	byte ptr [esi+0], 10h
		mov	byte ptr [esi+1], 0
		mov	byte ptr [esi+2], 1
		mov	byte ptr [esi+3], 0
		mov	dword ptr [esi+4], 46C77C00h
		push	es
; ---------------------------------------------------------------------------
		db    0
; ---------------------------------------------------------------------------
		add	[ebx-76FFF77Bh], cl
		xchg	cl, [eax]

loc_A7:					; CODE XREF: seg000:000000D9j
		add	[ebx-76FFF57Bh], cl
		xchg	cl, [edx]
		add	bh, al
		inc	esi
		or	al, 0
		add	bh, al
		inc	esi
		push	cs
; ---------------------------------------------------------------------------
		db    0
; ---------------------------------------------------------------------------
		add	[ecx-32BD4B12h], cl
		adc	esi, [ebx+24h]
		mov	esi, 0FDBF0756h
		push	es
		call	edi
		mov	dh, [ebp+1]
		mov	ecx, [ebp+1B80002h]
		add	cl, [edx+0BB1256h]
		jl	short near ptr loc_A7+1
		adc	esi, [ebx+8]
		mov	esi, 0FDBF0756h
		push	es
		call	edi
		mov	ebx, 878B7C00h
		inc	byte ptr [ecx]
		cmp	eax, 775AA55h
		mov	esi, edi
		jmp	far ptr	60BEh:7C00h
; ---------------------------------------------------------------------------
		pop	es
		mov	edi, 0D7FF0720h
		mov	esi, 20BF076Ch
		pop	es
		call	edi
		xor	eax, eax
		int	16h		; KEYBOARD - READ CHAR FROM BUFFER, WAIT IF EMPTY
					; Return: AH = scan code, AL = character
		xor	ebx, ebx
		mov	es, bx
		mov	ebx, 34B80472h
		adc	ah, [esi]
		mov	[edi], eax
		jmp	far ptr	3160h:0FFFF0000h
; ---------------------------------------------------------------------------

loc_122:				; CODE XREF: seg000:0000012Fj
		fld	tbyte ptr [eax+ecx-4BF68B40h]
		push	cs
		int	10h		; - VIDEO -
		lodsb
		or	al, al
		jnz	short near ptr loc_122+6
		popa
		retn
; ---------------------------------------------------------------------------
		dec	esi
		outsd
		and	[ecx+63h], ah
		jz	short near ptr unk_1A3
		jbe	short near ptr unk_1A1
		and	[ebp+6Eh], ah
		jz	short near ptr unk_1B3
		jns	short near ptr loc_162+1
; ---------------------------------------------------------------------------
		db  69h	; i
; ---------------------------------------------------------------------------
		outsb
		and	[ebp+42h], cl
		push	edx
		add	[ecx+6Eh], cl
		jbe	short near ptr unk_1AF
		insb
		imul	esp, [eax+4Dh],	49005242h
		das
		dec	edi
		and	[ebp+72h], ah
		jb	short near ptr unk_1CD
		jb	short $+2
		dec	ecx
		outsb

loc_162:				; CODE XREF: seg000:00000141j
		jbe	short loc_1C5
		insb
		imul	esp, [eax+50h],	0D005342h
		or	dl, [eax+72h]
		db	65h
		jnb	short near ptr unk_1E6
		and	[ecx+6Ch], ah
		insd
		outsd
		jnb	short near ptr unk_1EE
		and	[ecx+6Eh], ah
		jns	short near ptr unk_19F
		imul	esp, [ebp+79h],	20h
		jz	short near ptr unk_1F4
		and	[edx+65h], dh
		bound	ebp, [edi+6Fh]
		jz	short near ptr unk_1BB
		db	2Eh
		add	cs:[ebp+42h], cl
		push	edx
		db	2Eh, 2Eh
		add	cs:[eax], al
; ---------------------------------------------------------------------------
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
unk_19F		db    0			; CODE XREF: seg000:0000017Dj
		db    0
unk_1A1		db    0			; CODE XREF: seg000:0000013Aj
		db    0
unk_1A3		db    0			; CODE XREF: seg000:00000138j
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
unk_1AF		db    0			; CODE XREF: seg000:0000014Cj
		db    0
		db    0
		db    0
unk_1B3		db    0			; CODE XREF: seg000:0000013Fj
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
unk_1BB		db    0			; CODE XREF: seg000:0000018Bj
		db    0
		db    0
		db  80h	; €
		db    1
		db    1
		db    0
		db  39h	; 9
		db  3Fh	; ?
		db 0BFh	; ¿
; ---------------------------------------------------------------------------

loc_1C5:				; CODE XREF: seg000:loc_162j
		pop	es
		aas
; ---------------------------------------------------------------------------
		db    0
		db    0
		db    0
		db 0C1h
		db 0FDh	; ý
		db  1Fh
unk_1CD		db    0			; CODE XREF: seg000:0000015Cj
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
unk_1E6		db    0			; CODE XREF: seg000:00000170j
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
unk_1EE		db    0			; CODE XREF: seg000:00000178j
		db    0
		db    0
		db    0
		db    0
		db    0
unk_1F4		db    0			; CODE XREF: seg000:00000183j
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db    0
		db  55h	; U
		db 0AAh	; ª
seg000		ends


		end
